In [6]:
import pandas
import researchpy as rp
import seaborn as sns

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

# Analysis <font color=blue>after </font> combining RF, DT and SVM into 1C

In [24]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['dataset', 'time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "1c")
df.methods = df.methods.replace("['decision_tree']", "1c")
df.methods = df.methods.replace("['random_forest']", "1c")
fsIs_b = ['vowel', 'openml_phpJNxH0q', 'dataset_31_credit-g', 'dataset_40_sonar']
fsIs_m = ['solar-flare_1', 'wine-quality-red', 'dataset_39_ecoli', 'synthetic_control']
fsIl_b = ['AirlinesCodrnaAdult', 'MagicTelescope', 'electricity-normalized', 'phpmPOD5A']
fsIl_m = ['pokerhand-normalized', 'eye_movements', 'avila-tr']
flIs_b = ['audiology', 'arrhythmia', 'AP_Breast_Lung', 'AP_Omentum_Ovary']
flIs_m = ['Amazon', 'umistfacescropped', 'phpGUrE90']
flIl_b = ['gina_agnostic', 'hiva_agnostic', 'phpZrCzJR', 'phprAeXmK']
flIl_m = ['KDDCup99', 'connect-4', 'dataset_60_waveform-5000', 'dataset_186_satimage']
df_binary = df[df.dataset.isin(fsIs_b) | df.dataset.isin(fsIl_b) | df.dataset.isin(flIs_b) | df.dataset.isin(flIl_b)]
df_multi = df[df.dataset.isin(fsIs_m) | df.dataset.isin(fsIl_m) | df.dataset.isin(flIs_m) | df.dataset.isin(flIl_m)]
#df.drop(df[(df.methods=='fc') & ((df.time_budget==30) | (df.time_budget==10))].index, inplace=True)
#df.drop(df[(df.methods=='3c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df_binary.shape

(540, 4)

In [8]:
rp.summary_cont(df['f1score'])

  Variable      N      Mean        SD        SE  95% Conf.  Interval
0  f1score  900.0  0.766788  0.215177  0.007173   0.752711  0.780865

In [9]:
rp.summary_cont(df.groupby(['time_budget']))['f1score']

               N      Mean        SD        SE  95% Conf.  Interval
time_budget
10           300  0.748181  0.241727  0.013956   0.720827  0.775535
30           300  0.779510  0.202243  0.011677   0.756624  0.802396
60           300  0.772674  0.198329  0.011451   0.750231  0.795117

In [10]:
rp.summary_cont(df.groupby(['methods']))['f1score']

           N      Mean        SD        SE  95% Conf.  Interval
methods
1c       540  0.740979  0.237420  0.010217   0.720954  0.761004
3c       180  0.800090  0.173321  0.012919   0.774770  0.825411
fc       180  0.810914  0.166380  0.012401   0.786608  0.835221

In [11]:
rp.summary_cont(df.groupby(['time_budget', 'methods']))['f1score']

                       N      Mean        SD        SE  95% Conf.  Interval
time_budget methods
10          1c       180  0.710806  0.271346  0.020225   0.671165  0.750447
            3c        60  0.803653  0.175935  0.022713   0.759135  0.848171
            fc        60  0.804836  0.176436  0.022778   0.760192  0.849480
30          1c       180  0.759652  0.222612  0.016593   0.727130  0.792173
            3c        60  0.808447  0.163428  0.021098   0.767094  0.849799
            fc        60  0.810147  0.164981  0.021299   0.768401  0.851893
60          1c       180  0.752481  0.212487  0.015838   0.721438  0.783523
            3c        60  0.788171  0.182343  0.023540   0.742031  0.834310
            fc        60  0.817759  0.159848  0.020636   0.777312  0.858206

In [12]:
    # Fits the model with the interaction term
    # This will also automatically include the main effects for each factor
    model = ols('f1score ~ C(time_budget)*C(methods)', df).fit()

    # Seeing if the overall model is significant
    print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 8, 891) =  3.246, p =  0.0012

In [13]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.020
Method:                 Least Squares   F-statistic:                     3.246
Date:                Thu, 31 Oct 2019   Prob (F-statistic):            0.00119
Time:                        12:39:57   Log-Likelihood:                 119.05
No. Observations:                 900   AIC:                            -220.1
Df Residuals:                     891   BIC:                            -176.9
Df Model:                           8
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                 0.7108      0.016     44.760      0.000       0.680       0.742
C(time_budget)[T.30]                      0.0488      0.022      2.175      0.030       0.005       0.093
C(time_budget)[T.60]                      0.0417      0.022      1.856      0.064      -0.002       0.086
C(methods)[T.3c]                          0.0928      0.032      2.923      0.004       0.031       0.155
C(methods)[T.fc]                          0.0940      0.032      2.961      0.003       0.032       0.156
C(time_budget)[T.30]:C(methods)[T.3c]    -0.0441      0.045     -0.981      0.327      -0.132       0.044
C(time_budget)[T.60]:C(methods)[T.3c]    -0.0572      0.045     -1.273      0.204      -0.145       0.031
C(time_budget)[T.30]:C(methods)[T.fc]    -0.0435      0.045     -0.969      0.333      -0.132       0.045
C(time_budget)[T.60]:C(methods)[T.fc]    -0.0288      0.045     -0.640      0.522      -0.117       0.059
==============================================================================
Omnibus:                      208.057   Durbin-Watson:                   0.411
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              400.329
Skew:                          -1.349   Prob(JB):                     1.17e-87
Kurtosis:                       4.843   Cond. No.                         11.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [14]:
# Creates the ANOVA table
res = sm.stats.anova_lm(model, typ= 2)
res

                              sum_sq     df          F    PR(>F)
C(time_budget)              0.162811    2.0   1.793312  0.167008
C(methods)                  0.909795    2.0  10.021138  0.000050
C(time_budget):C(methods)   0.106176    4.0   0.584751  0.673758
Residual                   40.445886  891.0        NaN       NaN

In [15]:
# Fits the model
model2 = ols('f1score ~ C(time_budget)+ C(methods)', df).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 4, 895) =  5.918, p =  0.0001

In [16]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.026
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     5.918
Date:                Thu, 31 Oct 2019   Prob (F-statistic):           0.000106
Time:                        12:39:58   Log-Likelihood:                 117.87
No. Observations:                 900   AIC:                            -225.7
Df Residuals:                     895   BIC:                            -201.7
Df Model:                           4
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.7224      0.014     53.168      0.000       0.696       0.749
C(time_budget)[T.30]     0.0313      0.017      1.803      0.072      -0.003       0.065
C(time_budget)[T.60]     0.0245      0.017      1.409      0.159      -0.010       0.059
C(methods)[T.3c]         0.0591      0.018      3.227      0.001       0.023       0.095
C(methods)[T.fc]         0.0699      0.018      3.817      0.000       0.034       0.106
==============================================================================
Omnibus:                      211.460   Durbin-Watson:                   0.410
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              412.378
Skew:                          -1.362   Prob(JB):                     2.84e-90
Kurtosis:                       4.891   Cond. No.                         3.96
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [17]:
# Creates the ANOVA table
res2 = sm.stats.anova_lm(model2, typ= 2)
res2

                   sum_sq     df          F    PR(>F)
C(time_budget)   0.162811    2.0   1.796646  0.166452
C(methods)       0.909795    2.0  10.039770  0.000049
Residual        40.552063  895.0        NaN       NaN

In [18]:
# Calculating effect size
def anova_table(aov):
    aov['mean_sq'] = aov[:]['sum_sq']/aov[:]['df']
    
    aov['eta_sq'] = aov[:-1]['sum_sq']/sum(aov['sum_sq'])
    
    aov['omega_sq'] = (aov[:-1]['sum_sq']-(aov[:-1]['df']*aov['mean_sq'][-1]))/(sum(aov['sum_sq'])+aov['mean_sq'][-1])
    
    cols = ['sum_sq', 'mean_sq', 'df', 'F', 'PR(>F)', 'eta_sq', 'omega_sq']
    aov = aov[cols]
    return aov

anova_table(res2)

,sum_sq,mean_sq,df,F,PR(>F),eta_sq,omega_sq
C(time_budget),0.162811,0.081405,2.0,1.796646,0.166452,0.003911,0.001732
C(methods),0.909795,0.454898,2.0,10.039770,0.000049,0.021857,0.019659
Residual,40.552063,0.045310,895.0,NaN,NaN,NaN,NaN

In [19]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['methods'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
    1c     3c   0.0591 0.0038  0.0161 0.1022   True
    1c     fc   0.0699  0.001  0.0269  0.113   True
    3c     fc   0.0108 0.8681 -0.0419 0.0635  False
---------------------------------------------------

In [20]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['time_budget'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
    10     30   0.0313 0.1754 -0.0099 0.0725  False
    10     60   0.0245 0.3446 -0.0167 0.0657  False
    30     60  -0.0068    0.9  -0.048 0.0344  False
---------------------------------------------------

# Analysis <font color=blue>without </font> combining RF, DT and SVM into 1C

In [58]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "svm")
df.methods = df.methods.replace("['decision_tree']", "DT")
df.methods = df.methods.replace("['random_forest']", "RF")
#df.drop(df[(df.methods=='fc') & ((df.time_budget==30) | (df.time_budget==10))].index, inplace=True)
#df.drop(df[(df.methods=='3c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df.shape

(900, 3)

In [59]:
rp.summary_cont(df['f1score'])

  Variable      N      Mean        SD        SE  95% Conf.  Interval
0  f1score  900.0  0.766788  0.215177  0.007173   0.752711  0.780865

In [60]:
rp.summary_cont(df.groupby(['time_budget']))['f1score']

               N      Mean        SD        SE  95% Conf.  Interval
time_budget
10           300  0.748181  0.241727  0.013956   0.720827  0.775535
30           300  0.779510  0.202243  0.011677   0.756624  0.802396
60           300  0.772674  0.198329  0.011451   0.750231  0.795117

In [61]:
rp.summary_cont(df.groupby(['methods']))['f1score']

           N      Mean        SD        SE  95% Conf.  Interval
methods
3c       180  0.800090  0.173321  0.012919   0.774770  0.825411
DT       180  0.748380  0.206092  0.015361   0.718272  0.778487
RF       180  0.790741  0.187726  0.013992   0.763317  0.818166
fc       180  0.810914  0.166380  0.012401   0.786608  0.835221
svm      180  0.683817  0.293579  0.021882   0.640928  0.726706

In [62]:
rp.summary_cont(df.groupby(['time_budget', 'methods']))['f1score']

                      N      Mean        SD        SE  95% Conf.  Interval
time_budget methods
10          3c       60  0.803653  0.175935  0.022713   0.759135  0.848171
            DT       60  0.724580  0.230408  0.029746   0.666279  0.782882
            RF       60  0.771806  0.225808  0.029152   0.714668  0.828943
            fc       60  0.804836  0.176436  0.022778   0.760192  0.849480
            svm      60  0.636031  0.331123  0.042748   0.552245  0.719817
30          3c       60  0.808447  0.163428  0.021098   0.767094  0.849799
            DT       60  0.763262  0.197065  0.025441   0.713398  0.813127
            RF       60  0.814256  0.166306  0.021470   0.772174  0.856337
            fc       60  0.810147  0.164981  0.021299   0.768401  0.851893
            svm      60  0.701436  0.278144  0.035908   0.631056  0.771816
60          3c       60  0.788171  0.182343  0.023540   0.742031  0.834310
            DT       60  0.757296  0.189886  0.024514   0.709248  0.805344
            RF       60  0.786163  0.165295  0.021340   0.744338  0.827989
            fc       60  0.817759  0.159848  0.020636   0.777312  0.858206
            svm      60  0.713982  0.266306  0.034380   0.646598  0.781367

In [63]:
    # Fits the model with the interaction term
    # This will also automatically include the main effects for each factor
    model = ols('f1score ~ C(time_budget)*C(methods)', df).fit()

    # Seeing if the overall model is significant
    print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 14, 885) =  3.681, p =  0.0000

In [64]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.055
Model:                            OLS   Adj. R-squared:                  0.040
Method:                 Least Squares   F-statistic:                     3.681
Date:                Wed, 23 Oct 2019   Prob (F-statistic):           5.19e-06
Time:                        14:44:13   Log-Likelihood:                 131.59
No. Observations:                 900   AIC:                            -233.2
Df Residuals:                     885   BIC:                            -161.1
Df Model:                          14
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                  0.8037      0.027     29.528      0.000       0.750       0.857
C(time_budget)[T.30]                       0.0048      0.038      0.125      0.901      -0.071       0.080
C(time_budget)[T.60]                      -0.0155      0.038     -0.402      0.688      -0.091       0.060
C(methods)[T.DT]                          -0.0791      0.038     -2.054      0.040      -0.155      -0.004
C(methods)[T.RF]                          -0.0318      0.038     -0.827      0.408      -0.107       0.044
C(methods)[T.fc]                           0.0012      0.038      0.031      0.975      -0.074       0.077
C(methods)[T.svm]                         -0.1676      0.038     -4.355      0.000      -0.243      -0.092
C(time_budget)[T.30]:C(methods)[T.DT]      0.0339      0.054      0.623      0.534      -0.073       0.141
C(time_budget)[T.60]:C(methods)[T.DT]      0.0482      0.054      0.885      0.376      -0.059       0.155
C(time_budget)[T.30]:C(methods)[T.RF]      0.0377      0.054      0.692      0.489      -0.069       0.144
C(time_budget)[T.60]:C(methods)[T.RF]      0.0298      0.054      0.548      0.584      -0.077       0.137
C(time_budget)[T.30]:C(methods)[T.fc]      0.0005      0.054      0.010      0.992      -0.106       0.107
C(time_budget)[T.60]:C(methods)[T.fc]      0.0284      0.054      0.522      0.602      -0.078       0.135
C(time_budget)[T.30]:C(methods)[T.svm]     0.0606      0.054      1.113      0.266      -0.046       0.167
C(time_budget)[T.60]:C(methods)[T.svm]     0.0934      0.054      1.716      0.086      -0.013       0.200
==============================================================================
Omnibus:                      175.479   Durbin-Watson:                   0.391
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              300.420
Skew:                          -1.214   Prob(JB):                     5.81e-66
Kurtosis:                       4.453   Cond. No.                         21.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [65]:
# Creates the ANOVA table
res = sm.stats.anova_lm(model, typ= 2)
res

                              sum_sq     df          F        PR(>F)
C(time_budget)              0.162811    2.0   1.831571  1.607684e-01
C(methods)                  1.953545    4.0  10.988406  1.062220e-08
C(time_budget):C(methods)   0.173953    8.0   0.489230  8.644070e-01
Residual                   39.334360  885.0        NaN           NaN

In [66]:
# Fits the model
model2 = ols('f1score ~ C(time_budget)+ C(methods)', df).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 6, 893) =  7.973, p =  0.0000

In [67]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.051
Model:                            OLS   Adj. R-squared:                  0.044
Method:                 Least Squares   F-statistic:                     7.973
Date:                Wed, 23 Oct 2019   Prob (F-statistic):           2.15e-08
Time:                        14:44:15   Log-Likelihood:                 129.60
No. Observations:                 900   AIC:                            -245.2
Df Residuals:                     893   BIC:                            -211.6
Df Model:                           6
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.7815      0.019     42.128      0.000       0.745       0.818
C(time_budget)[T.30]     0.0313      0.017      1.824      0.068      -0.002       0.065
C(time_budget)[T.60]     0.0245      0.017      1.426      0.154      -0.009       0.058
C(methods)[T.DT]        -0.0517      0.022     -2.332      0.020      -0.095      -0.008
C(methods)[T.RF]        -0.0093      0.022     -0.422      0.673      -0.053       0.034
C(methods)[T.fc]         0.0108      0.022      0.488      0.626      -0.033       0.054
C(methods)[T.svm]       -0.1163      0.022     -5.244      0.000      -0.160      -0.073
==============================================================================
Omnibus:                      179.446   Durbin-Watson:                   0.391
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              311.465
Skew:                          -1.231   Prob(JB):                     2.32e-68
Kurtosis:                       4.497   Cond. No.                         6.45
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [68]:
# Creates the ANOVA table
res2 = sm.stats.anova_lm(model2, typ= 2)
res2

                   sum_sq     df          F        PR(>F)
C(time_budget)   0.162811    2.0   1.839990  1.594206e-01
C(methods)       1.953545    4.0  11.038917  9.647179e-09
Residual        39.508313  893.0        NaN           NaN

In [69]:
# Calculating effect size
def anova_table(aov):
    aov['mean_sq'] = aov[:]['sum_sq']/aov[:]['df']
    
    aov['eta_sq'] = aov[:-1]['sum_sq']/sum(aov['sum_sq'])
    
    aov['omega_sq'] = (aov[:-1]['sum_sq']-(aov[:-1]['df']*aov['mean_sq'][-1]))/(sum(aov['sum_sq'])+aov['mean_sq'][-1])
    
    cols = ['sum_sq', 'mean_sq', 'df', 'F', 'PR(>F)', 'eta_sq', 'omega_sq']
    aov = aov[cols]
    return aov

anova_table(res2)

,sum_sq,mean_sq,df,F,PR(>F),eta_sq,omega_sq
C(time_budget),0.162811,0.081405,2.0,1.839990,1.594206e-01,0.003911,0.001784
C(methods),1.953545,0.488386,4.0,11.038917,9.647179e-09,0.046932,0.042636
Residual,39.508313,0.044242,893.0,NaN,NaN,NaN,NaN

In [70]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['methods'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
  3c     DT   -0.0517  -0.1124  0.0089 False
  3c     RF   -0.0093   -0.07   0.0513 False
  3c     fc    0.0108  -0.0498  0.0715 False
  3c    svm   -0.1163  -0.1769 -0.0556  True
  DT     RF    0.0424  -0.0183  0.103  False
  DT     fc    0.0625   0.0019  0.1232  True
  DT    svm   -0.0646  -0.1252 -0.0039  True
  RF     fc    0.0202  -0.0405  0.0808 False
  RF    svm   -0.1069  -0.1676 -0.0463  True
  fc    svm   -0.1271  -0.1878 -0.0664  True
---------------------------------------------

# Analysis <font color=blue>after </font> combining RF, DT and SVM into 1C 
# Comparing FC (60 min) with 3C(30)

In [95]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "1c")
df.methods = df.methods.replace("['decision_tree']", "1c")
df.methods = df.methods.replace("['random_forest']", "1c")
df.drop(df[(df.methods=='fc') & ((df.time_budget==30) | (df.time_budget==10))].index, inplace=True)
df.drop(df[(df.methods=='3c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df.drop(df[(df.methods=='1c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df.shape

(300, 3)

In [96]:
rp.summary_cont(df['f1score'])

  Variable      N      Mean        SD        SE  95% Conf.  Interval
0  f1score  300.0  0.781032  0.201683  0.011644   0.758117  0.803947

In [97]:
rp.summary_cont(df.groupby(['time_budget']))['f1score']

               N      Mean        SD        SE  95% Conf.  Interval
time_budget
30           240  0.771850  0.210135  0.013564   0.745264  0.798436
60            60  0.817759  0.159848  0.020636   0.777312  0.858206

In [98]:
rp.summary_cont(df.groupby(['methods']))['f1score']

           N      Mean        SD        SE  95% Conf.  Interval
methods
1c       180  0.759652  0.222612  0.016593   0.727130  0.792173
3c        60  0.808447  0.163428  0.021098   0.767094  0.849799
fc        60  0.817759  0.159848  0.020636   0.777312  0.858206

In [99]:
rp.summary_cont(df.groupby(['time_budget', 'methods']))['f1score']

                       N      Mean        SD        SE  95% Conf.  Interval
time_budget methods
30          1c       180  0.759652  0.222612  0.016593   0.727130  0.792173
            3c        60  0.808447  0.163428  0.021098   0.767094  0.849799
60          fc        60  0.817759  0.159848  0.020636   0.777312  0.858206

In [100]:
    # Fits the model with the interaction term
    # This will also automatically include the main effects for each factor
    model = ols('f1score ~ C(time_budget)*C(methods)', df).fit()

    # Seeing if the overall model is significant
    print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 2, 297) =  2.588, p =  0.0769

In [101]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.017
Model:                            OLS   Adj. R-squared:                  0.011
Method:                 Least Squares   F-statistic:                     2.588
Date:                Wed, 23 Oct 2019   Prob (F-statistic):             0.0769
Time:                        15:04:11   Log-Likelihood:                 57.728
No. Observations:                 300   AIC:                            -109.5
Df Residuals:                     297   BIC:                            -98.34
Df Model:                           2
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                 0.7597      0.015     50.801      0.000       0.730       0.789
C(time_budget)[T.60]                      0.0194      0.010      1.943      0.053      -0.000       0.039
C(methods)[T.3c]                          0.0488      0.030      1.632      0.104      -0.010       0.108
C(methods)[T.fc]                          0.0194      0.010      1.943      0.053      -0.000       0.039
C(time_budget)[T.60]:C(methods)[T.3c]          0          0        nan        nan           0           0
C(time_budget)[T.60]:C(methods)[T.fc]     0.0194      0.010      1.943      0.053      -0.000       0.039
==============================================================================
Omnibus:                       74.811   Durbin-Watson:                   0.470
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              138.633
Skew:                          -1.338   Prob(JB):                     7.88e-31
Kurtosis:                       4.982   Cond. No.                          inf
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is      0. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [102]:
# Creates the ANOVA table
res = sm.stats.anova_lm(model, typ= 2)
res

C:\Users\HassanEldeeb\Anaconda3\lib\site-packages\statsmodels\base\model.py:1532: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 1, but rank is 0
  'rank is %d' % (J, J_), ValueWarning)
C:\Users\HassanEldeeb\Anaconda3\lib\site-packages\statsmodels\base\model.py:1532: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 2, but rank is 1
  'rank is %d' % (J, J_), ValueWarning)
C:\Users\HassanEldeeb\Anaconda3\lib\site-packages\statsmodels\base\model.py:1532: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 2, but rank is 1
  'rank is %d' % (J, J_), ValueWarning)

                                 sum_sq     df             F    PR(>F)
C(time_budget)                      NaN    1.0           NaN       NaN
C(methods)                 3.370358e-17    2.0  4.186913e-16  1.000000
C(time_budget):C(methods)  3.038849e-01    2.0  3.775087e+00  0.052966
Residual                   1.195387e+01  297.0           NaN       NaN

In [103]:
# Fits the model
model2 = ols('f1score ~ C(time_budget)+ C(methods)', df).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 2, 297) =  2.588, p =  0.0769

In [81]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.022
Model:                            OLS   Adj. R-squared:                  0.017
Method:                 Least Squares   F-statistic:                     3.765
Date:                Wed, 23 Oct 2019   Prob (F-statistic):            0.00488
Time:                        14:45:28   Log-Likelihood:                 49.945
No. Observations:                 660   AIC:                            -89.89
Df Residuals:                     655   BIC:                            -67.43
Df Model:                           4
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.7108      0.017     42.349      0.000       0.678       0.744
C(time_budget)[T.30]     0.0488      0.024      2.058      0.040       0.002       0.095
C(time_budget)[T.60]     0.0417      0.024      1.756      0.080      -0.005       0.088
C(methods)[T.3c]         0.0488      0.034      1.454      0.147      -0.017       0.115
C(methods)[T.fc]         0.0653      0.034      1.945      0.052      -0.001       0.131
==============================================================================
Omnibus:                      156.110   Durbin-Watson:                   0.424
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              294.256
Skew:                          -1.371   Prob(JB):                     1.27e-64
Kurtosis:                       4.782   Cond. No.                         4.79
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [82]:
# Creates the ANOVA table
res2 = sm.stats.anova_lm(model2, typ= 2)
res2

                   sum_sq     df         F    PR(>F)
C(time_budget)   0.250448    2.0  2.469388  0.085424
C(methods)       0.298902    2.0  2.947136  0.053186
Residual        33.215397  655.0       NaN       NaN

In [83]:
# Calculating effect size
def anova_table(aov):
    aov['mean_sq'] = aov[:]['sum_sq']/aov[:]['df']
    
    aov['eta_sq'] = aov[:-1]['sum_sq']/sum(aov['sum_sq'])
    
    aov['omega_sq'] = (aov[:-1]['sum_sq']-(aov[:-1]['df']*aov['mean_sq'][-1]))/(sum(aov['sum_sq'])+aov['mean_sq'][-1])
    
    cols = ['sum_sq', 'mean_sq', 'df', 'F', 'PR(>F)', 'eta_sq', 'omega_sq']
    aov = aov[cols]
    return aov

anova_table(res2)

,sum_sq,mean_sq,df,F,PR(>F),eta_sq,omega_sq
C(time_budget),0.250448,0.125224,2.0,2.469388,0.085424,0.007417,0.004407
C(methods),0.298902,0.149451,2.0,2.947136,0.053186,0.008852,0.005840
Residual,33.215397,0.050711,655.0,NaN,NaN,NaN,NaN

In [84]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['methods'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD,FWER=0.05
============================================
group1 group2 meandiff  lower  upper  reject
--------------------------------------------
  1C     3c    0.0675  -0.0047 0.1396 False
  1C     fc    0.0768   0.0046 0.1489  True
  3c     fc    0.0093  -0.0875 0.1061 False
--------------------------------------------

# Wilcoxon signed-rank test

In [87]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "svm")
df.methods = df.methods.replace("['decision_tree']", "DT")
df.methods = df.methods.replace("['random_forest']", "RF")
df.shape

(900, 3)

In [89]:
# Wilcoxon signed-rank test
from numpy.random import seed
from numpy.random import randn
from scipy.stats import wilcoxon
# seed the random number generator
seed(1)
# generate two independent samples
data1 = df.f1score[df.methods=='3c']
data2 = df.f1score[df.methods=='fc']
# compare samples
stat, p = wilcoxon(data1, data2)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
    print('Same distribution (fail to reject H0)')
else:
    print('Different distribution (reject H0)')

Statistics=5989.500, p=0.006
Different distribution (reject H0)

In [92]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "svm")
df.methods = df.methods.replace("['decision_tree']", "DT")
df.methods = df.methods.replace("['random_forest']", "RF")
df.shape

(900, 3)

In [94]:
# Wilcoxon signed-rank test
from numpy.random import seed
from numpy.random import randn
from scipy.stats import wilcoxon
# seed the random number generator
seed(1)
# generate two independent samples
data1 = df.f1score[df.methods=='3c']
data2 = df.f1score[df.methods=='fc']
# compare samples
stat, p = wilcoxon(data1, data2)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
    print('Same distribution (fail to reject H0)')
else:
    print('Different distribution (reject H0)')

Statistics=5989.500, p=0.006
Different distribution (reject H0)