In [41]:
import pandas as pd
import numpy as np
import researchpy as rp
import seaborn as sns
import os
import ast

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

# Analysis <font color=blue>after </font> combining RF, DT and SVM into 1C

In [102]:
def get_class (model):
    if isinstance(model, str):
        model = '{' +'}'.join('{'.join(model.split('{')[1:]).split('}')[0:1]) + '}'
        m = ast.literal_eval(model)
        if 'classifier:__choice__' in m:
            classifier = m['classifier:__choice__']
        else:
            classifier = ''
        return classifier
    else:
        return ''


def parse_tpot(directory):
    result = pd.DataFrame(columns=['dataset', 'accuracy', 'model', 'precision', 'recall', 'f1score', 'time_budget', 'methods'])
    for subdir, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith('.csv'):
                method = file.split('.')[0].split('_')[2]
                time_budget = file.split('.')[0].split('_')[3]
                run = []
                sub_result = pd.read_csv(os.path.join(subdir, file))
                sub_result.rename(columns={'Unnamed: 0': 'dataset'}, inplace = True)
                run.append(sub_result[['dataset', 'accuracy_1', 'model_1', 'precision_1', 'recall_1', 'f1score_1']])
                run.append(sub_result[['dataset', 'accuracy_2', 'model_2', 'precision_2', 'recall_2', 'f1score_2']])
                run.append(sub_result[['dataset', 'accuracy_3', 'model_3', 'precision_3', 'recall_3', 'f1score_3']])
                for i in range(3):
                    run[i].rename(columns={'accuracy_'+str(i+1): 'accuracy',
                                           'model_'+str(i+1): 'model',
                                           'precision_'+str(i+1): 'precision',
                                           'recall_'+str(i+1): 'recall',
                                           'f1score_'+str(i+1): 'f1score'}, inplace=True)
                    run[i]['methods'] = str(method)
                    run[i]['time_budget'] = int(time_budget)
                    result = pd.concat([result, run[i]], axis=0, sort=True, ignore_index=True)
    result.model = result.model.apply(get_class)
    result = result[~np.isnan(result.f1score)]
    return result
parse_tpot(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/")

C:\Users\HassanEldeeb\Anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HassanEldeeb\Anaconda3\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,accuracy,dataset,f1score,methods,model,precision,recall,time_budget
0,0.949153,AP_Breast_Lung,0.911765,3C,,0.911765,0.911765,10
4,0.947368,audiology,0.918919,3C,,0.944444,0.894737,10
5,0.700000,dataset_31_credit-g,0.788732,3C,,0.782123,0.795455,10
7,0.900807,gina_agnostic,0.892500,3C,,0.915385,0.870732,10
8,0.965974,hiva_agnostic,0.333333,3C,,0.692308,0.219512,10
...,...,...,...,...,...,...,...,...
891,0.597500,wine-quality-red,0.597500,SVC,,0.597500,0.597500,60
895,0.395026,eye_movements,0.395026,SVC,,0.395026,0.395026,60
897,0.645570,solar-flare_1,0.645570,SVC,,0.645570,0.645570,60
898,0.166667,umistfacescropped,0.166667,SVC,,0.166667,0.166667,60
899,0.597500,wine-quality-red,0.597500,SVC,,0.597500,0.597500,60

In [131]:
df = parse_tpot(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/")
df = df[['dataset', 'time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("default", "fc")
df.methods = df.methods.replace("SVC", "1c")
df.methods = df.methods.replace("DT", "1c")
df.methods = df.methods.replace("RF", "1c")
fsIs_b = ['vowel', 'openml_phpJNxH0q', 'dataset_31_credit-g', 'dataset_40_sonar']
fsIs_m = ['solar-flare_1', 'wine-quality-red', 'dataset_39_ecoli', 'synthetic_control']
fsIl_b = ['AirlinesCodrnaAdult', 'MagicTelescope', 'electricity-normalized', 'phpmPOD5A']
fsIl_m = ['pokerhand-normalized', 'eye_movements', 'avila-tr']
flIs_b = ['audiology', 'arrhythmia', 'AP_Breast_Lung', 'AP_Omentum_Ovary']
flIs_m = ['Amazon', 'umistfacescropped', 'phpGUrE90']
flIl_b = ['gina_agnostic', 'hiva_agnostic', 'phpZrCzJR', 'phprAeXmK']
flIl_m = ['KDDCup99', 'connect-4', 'dataset_60_waveform-5000', 'dataset_186_satimage']
df_binary = df[df.dataset.isin(fsIs_b) | df.dataset.isin(fsIl_b) | df.dataset.isin(flIs_b) | df.dataset.isin(flIl_b)]
df_multi = df[df.dataset.isin(fsIs_m) | df.dataset.isin(fsIl_m) | df.dataset.isin(flIs_m) | df.dataset.isin(flIl_m)]
#df.drop(df[(df.methods=='fc') & ((df.time_budget==30) | (df.time_budget==10))].index, inplace=True)
#df.drop(df[(df.methods=='3c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df.shape

C:\Users\HassanEldeeb\Anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HassanEldeeb\Anaconda3\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

(524, 4)

In [132]:
rp.summary_cont(df['f1score'])

  Variable      N      Mean        SD        SE  95% Conf.  Interval
0  f1score  524.0  0.708253  0.270415  0.011813   0.685046   0.73146

In [133]:
rp.summary_cont(df.groupby(['time_budget']))['f1score']

               N      Mean        SD        SE  95% Conf.  Interval
time_budget
10           157  0.716536  0.268588  0.021436   0.674522  0.758550
30           173  0.701214  0.273636  0.020804   0.660438  0.741990
60           194  0.707828  0.270216  0.019400   0.669803  0.745853

In [134]:
rp.summary_cont(df.groupby(['methods']))['f1score']

           N      Mean        SD        SE  95% Conf.  Interval
methods
1c       288  0.632771  0.304980  0.017971   0.597548  0.667994
3C       103  0.798783  0.193445  0.019061   0.761424  0.836142
fc       133  0.801595  0.175995  0.015261   0.771684  0.831506

In [135]:
rp.summary_cont(df.groupby(['time_budget', 'methods']))['f1score']

                       N      Mean        SD        SE  95% Conf.  Interval
time_budget methods
10          1c        89  0.652341  0.299258  0.031721   0.590167  0.714515
            3C        33  0.813610  0.195320  0.034001   0.746968  0.880251
            fc        35  0.788248  0.195113  0.032980   0.723606  0.852889
30          1c        97  0.624742  0.306579  0.031128   0.563730  0.685754
            3C        31  0.800087  0.196350  0.035266   0.730966  0.869207
            fc        45  0.797940  0.178865  0.026664   0.745680  0.850201
60          1c       102  0.623331  0.310561  0.030750   0.563061  0.683601
            3C        39  0.785200  0.193653  0.031009   0.724422  0.845978
            fc        53  0.813511  0.162445  0.022314   0.769777  0.857246

In [136]:
    # Fits the model with the interaction term
    # This will also automatically include the main effects for each factor
    model = ols('f1score ~ C(time_budget)*C(methods)', df).fit()

    # Seeing if the overall model is significant
    print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 8, 515) =  6.941, p =  0.0000

In [137]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.097
Model:                            OLS   Adj. R-squared:                  0.083
Method:                 Least Squares   F-statistic:                     6.941
Date:                Fri, 01 Nov 2019   Prob (F-statistic):           1.06e-08
Time:                        21:53:04   Log-Likelihood:                -30.911
No. Observations:                 524   AIC:                             79.82
Df Residuals:                     515   BIC:                             118.2
Df Model:                           8
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                 0.6523      0.027     23.770      0.000       0.598       0.706
C(time_budget)[T.30]                     -0.0276      0.038     -0.726      0.468      -0.102       0.047
C(time_budget)[T.60]                     -0.0290      0.038     -0.772      0.440      -0.103       0.045
C(methods)[T.3C]                          0.1613      0.053      3.056      0.002       0.058       0.265
C(methods)[T.fc]                          0.1359      0.052      2.631      0.009       0.034       0.237
C(time_budget)[T.30]:C(methods)[T.3C]     0.0141      0.075      0.187      0.851      -0.133       0.162
C(time_budget)[T.60]:C(methods)[T.3C]     0.0006      0.072      0.008      0.993      -0.141       0.142
C(time_budget)[T.30]:C(methods)[T.fc]     0.0373      0.070      0.536      0.593      -0.100       0.174
C(time_budget)[T.60]:C(methods)[T.fc]     0.0543      0.068      0.801      0.423      -0.079       0.187
==============================================================================
Omnibus:                       53.380   Durbin-Watson:                   2.146
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               68.154
Skew:                          -0.882   Prob(JB):                     1.59e-15
Kurtosis:                       3.097   Cond. No.                         12.5
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [138]:
# Creates the ANOVA table
res = sm.stats.anova_lm(model, typ= 2)
res

                              sum_sq     df          F        PR(>F)
C(time_budget)              0.028413    2.0   0.211929  8.090925e-01
C(methods)                  3.652856    2.0  27.246700  5.649659e-12
C(time_budget):C(methods)   0.049880    4.0   0.186029  9.456628e-01
Residual                   34.521997  515.0        NaN           NaN

In [139]:
# Fits the model
model2 = ols('f1score ~ C(time_budget)+ C(methods)', df).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 4, 519) =  13.782, p =  0.0000

In [140]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.096
Model:                            OLS   Adj. R-squared:                  0.089
Method:                 Least Squares   F-statistic:                     13.78
Date:                Fri, 01 Nov 2019   Prob (F-statistic):           1.09e-10
Time:                        21:53:05   Log-Likelihood:                -31.290
No. Observations:                 524   AIC:                             72.58
Df Residuals:                     519   BIC:                             93.89
Df Model:                           4
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.6439      0.023     28.202      0.000       0.599       0.689
C(time_budget)[T.30]    -0.0165      0.028     -0.579      0.563      -0.072       0.039
C(time_budget)[T.60]    -0.0157      0.028     -0.566      0.571      -0.070       0.039
C(methods)[T.3C]         0.1658      0.030      5.593      0.000       0.108       0.224
C(methods)[T.fc]         0.1695      0.027      6.259      0.000       0.116       0.223
==============================================================================
Omnibus:                       53.684   Durbin-Watson:                   2.144
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               68.619
Skew:                          -0.885   Prob(JB):                     1.26e-15
Kurtosis:                       3.104   Cond. No.                         4.17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [141]:
# Creates the ANOVA table
res2 = sm.stats.anova_lm(model2, typ= 2)
res2

                   sum_sq     df          F        PR(>F)
C(time_budget)   0.028413    2.0   0.213267  8.080111e-01
C(methods)       3.652856    2.0  27.418708  4.788721e-12
Residual        34.571878  519.0        NaN           NaN

In [142]:
# Calculating effect size
def anova_table(aov):
    aov['mean_sq'] = aov[:]['sum_sq']/aov[:]['df']
    
    aov['eta_sq'] = aov[:-1]['sum_sq']/sum(aov['sum_sq'])
    
    aov['omega_sq'] = (aov[:-1]['sum_sq']-(aov[:-1]['df']*aov['mean_sq'][-1]))/(sum(aov['sum_sq'])+aov['mean_sq'][-1])
    
    cols = ['sum_sq', 'mean_sq', 'df', 'F', 'PR(>F)', 'eta_sq', 'omega_sq']
    aov = aov[cols]
    return aov

anova_table(res2)

,sum_sq,mean_sq,df,F,PR(>F),eta_sq,omega_sq
C(time_budget),0.028413,0.014206,2.0,0.213267,8.080111e-01,0.000743,-0.002735
C(methods),3.652856,1.826428,2.0,27.418708,4.788721e-12,0.095492,0.091849
Residual,34.571878,0.066612,519.0,NaN,NaN,NaN,NaN

In [143]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['methods'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
==================================================
group1 group2 meandiff p-adj  lower  upper  reject
--------------------------------------------------
    1c     3C    0.166 0.001  0.0965 0.2356   True
    1c     fc   0.1688 0.001  0.1053 0.2323   True
    3C     fc   0.0028   0.9 -0.0767 0.0823  False
--------------------------------------------------

In [144]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['time_budget'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
    10     30  -0.0153 0.8504 -0.0855 0.0549  False
    10     60  -0.0087    0.9 -0.0771 0.0596  False
    30     60   0.0066    0.9   -0.06 0.0732  False
---------------------------------------------------

# Analysis <font color=blue>without </font> combining RF, DT and SVM into 1C

In [58]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "svm")
df.methods = df.methods.replace("['decision_tree']", "DT")
df.methods = df.methods.replace("['random_forest']", "RF")
#df.drop(df[(df.methods=='fc') & ((df.time_budget==30) | (df.time_budget==10))].index, inplace=True)
#df.drop(df[(df.methods=='3c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df.shape

(900, 3)

In [59]:
rp.summary_cont(df['f1score'])

  Variable      N      Mean        SD        SE  95% Conf.  Interval
0  f1score  900.0  0.766788  0.215177  0.007173   0.752711  0.780865

In [60]:
rp.summary_cont(df.groupby(['time_budget']))['f1score']

               N      Mean        SD        SE  95% Conf.  Interval
time_budget
10           300  0.748181  0.241727  0.013956   0.720827  0.775535
30           300  0.779510  0.202243  0.011677   0.756624  0.802396
60           300  0.772674  0.198329  0.011451   0.750231  0.795117

In [61]:
rp.summary_cont(df.groupby(['methods']))['f1score']

           N      Mean        SD        SE  95% Conf.  Interval
methods
3c       180  0.800090  0.173321  0.012919   0.774770  0.825411
DT       180  0.748380  0.206092  0.015361   0.718272  0.778487
RF       180  0.790741  0.187726  0.013992   0.763317  0.818166
fc       180  0.810914  0.166380  0.012401   0.786608  0.835221
svm      180  0.683817  0.293579  0.021882   0.640928  0.726706

In [62]:
rp.summary_cont(df.groupby(['time_budget', 'methods']))['f1score']

                      N      Mean        SD        SE  95% Conf.  Interval
time_budget methods
10          3c       60  0.803653  0.175935  0.022713   0.759135  0.848171
            DT       60  0.724580  0.230408  0.029746   0.666279  0.782882
            RF       60  0.771806  0.225808  0.029152   0.714668  0.828943
            fc       60  0.804836  0.176436  0.022778   0.760192  0.849480
            svm      60  0.636031  0.331123  0.042748   0.552245  0.719817
30          3c       60  0.808447  0.163428  0.021098   0.767094  0.849799
            DT       60  0.763262  0.197065  0.025441   0.713398  0.813127
            RF       60  0.814256  0.166306  0.021470   0.772174  0.856337
            fc       60  0.810147  0.164981  0.021299   0.768401  0.851893
            svm      60  0.701436  0.278144  0.035908   0.631056  0.771816
60          3c       60  0.788171  0.182343  0.023540   0.742031  0.834310
            DT       60  0.757296  0.189886  0.024514   0.709248  0.805344
            RF       60  0.786163  0.165295  0.021340   0.744338  0.827989
            fc       60  0.817759  0.159848  0.020636   0.777312  0.858206
            svm      60  0.713982  0.266306  0.034380   0.646598  0.781367

In [63]:
    # Fits the model with the interaction term
    # This will also automatically include the main effects for each factor
    model = ols('f1score ~ C(time_budget)*C(methods)', df).fit()

    # Seeing if the overall model is significant
    print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 14, 885) =  3.681, p =  0.0000

In [64]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.055
Model:                            OLS   Adj. R-squared:                  0.040
Method:                 Least Squares   F-statistic:                     3.681
Date:                Wed, 23 Oct 2019   Prob (F-statistic):           5.19e-06
Time:                        14:44:13   Log-Likelihood:                 131.59
No. Observations:                 900   AIC:                            -233.2
Df Residuals:                     885   BIC:                            -161.1
Df Model:                          14
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                  0.8037      0.027     29.528      0.000       0.750       0.857
C(time_budget)[T.30]                       0.0048      0.038      0.125      0.901      -0.071       0.080
C(time_budget)[T.60]                      -0.0155      0.038     -0.402      0.688      -0.091       0.060
C(methods)[T.DT]                          -0.0791      0.038     -2.054      0.040      -0.155      -0.004
C(methods)[T.RF]                          -0.0318      0.038     -0.827      0.408      -0.107       0.044
C(methods)[T.fc]                           0.0012      0.038      0.031      0.975      -0.074       0.077
C(methods)[T.svm]                         -0.1676      0.038     -4.355      0.000      -0.243      -0.092
C(time_budget)[T.30]:C(methods)[T.DT]      0.0339      0.054      0.623      0.534      -0.073       0.141
C(time_budget)[T.60]:C(methods)[T.DT]      0.0482      0.054      0.885      0.376      -0.059       0.155
C(time_budget)[T.30]:C(methods)[T.RF]      0.0377      0.054      0.692      0.489      -0.069       0.144
C(time_budget)[T.60]:C(methods)[T.RF]      0.0298      0.054      0.548      0.584      -0.077       0.137
C(time_budget)[T.30]:C(methods)[T.fc]      0.0005      0.054      0.010      0.992      -0.106       0.107
C(time_budget)[T.60]:C(methods)[T.fc]      0.0284      0.054      0.522      0.602      -0.078       0.135
C(time_budget)[T.30]:C(methods)[T.svm]     0.0606      0.054      1.113      0.266      -0.046       0.167
C(time_budget)[T.60]:C(methods)[T.svm]     0.0934      0.054      1.716      0.086      -0.013       0.200
==============================================================================
Omnibus:                      175.479   Durbin-Watson:                   0.391
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              300.420
Skew:                          -1.214   Prob(JB):                     5.81e-66
Kurtosis:                       4.453   Cond. No.                         21.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [65]:
# Creates the ANOVA table
res = sm.stats.anova_lm(model, typ= 2)
res

                              sum_sq     df          F        PR(>F)
C(time_budget)              0.162811    2.0   1.831571  1.607684e-01
C(methods)                  1.953545    4.0  10.988406  1.062220e-08
C(time_budget):C(methods)   0.173953    8.0   0.489230  8.644070e-01
Residual                   39.334360  885.0        NaN           NaN

In [66]:
# Fits the model
model2 = ols('f1score ~ C(time_budget)+ C(methods)', df).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 6, 893) =  7.973, p =  0.0000

In [67]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.051
Model:                            OLS   Adj. R-squared:                  0.044
Method:                 Least Squares   F-statistic:                     7.973
Date:                Wed, 23 Oct 2019   Prob (F-statistic):           2.15e-08
Time:                        14:44:15   Log-Likelihood:                 129.60
No. Observations:                 900   AIC:                            -245.2
Df Residuals:                     893   BIC:                            -211.6
Df Model:                           6
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.7815      0.019     42.128      0.000       0.745       0.818
C(time_budget)[T.30]     0.0313      0.017      1.824      0.068      -0.002       0.065
C(time_budget)[T.60]     0.0245      0.017      1.426      0.154      -0.009       0.058
C(methods)[T.DT]        -0.0517      0.022     -2.332      0.020      -0.095      -0.008
C(methods)[T.RF]        -0.0093      0.022     -0.422      0.673      -0.053       0.034
C(methods)[T.fc]         0.0108      0.022      0.488      0.626      -0.033       0.054
C(methods)[T.svm]       -0.1163      0.022     -5.244      0.000      -0.160      -0.073
==============================================================================
Omnibus:                      179.446   Durbin-Watson:                   0.391
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              311.465
Skew:                          -1.231   Prob(JB):                     2.32e-68
Kurtosis:                       4.497   Cond. No.                         6.45
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [68]:
# Creates the ANOVA table
res2 = sm.stats.anova_lm(model2, typ= 2)
res2

                   sum_sq     df          F        PR(>F)
C(time_budget)   0.162811    2.0   1.839990  1.594206e-01
C(methods)       1.953545    4.0  11.038917  9.647179e-09
Residual        39.508313  893.0        NaN           NaN

In [69]:
# Calculating effect size
def anova_table(aov):
    aov['mean_sq'] = aov[:]['sum_sq']/aov[:]['df']
    
    aov['eta_sq'] = aov[:-1]['sum_sq']/sum(aov['sum_sq'])
    
    aov['omega_sq'] = (aov[:-1]['sum_sq']-(aov[:-1]['df']*aov['mean_sq'][-1]))/(sum(aov['sum_sq'])+aov['mean_sq'][-1])
    
    cols = ['sum_sq', 'mean_sq', 'df', 'F', 'PR(>F)', 'eta_sq', 'omega_sq']
    aov = aov[cols]
    return aov

anova_table(res2)

,sum_sq,mean_sq,df,F,PR(>F),eta_sq,omega_sq
C(time_budget),0.162811,0.081405,2.0,1.839990,1.594206e-01,0.003911,0.001784
C(methods),1.953545,0.488386,4.0,11.038917,9.647179e-09,0.046932,0.042636
Residual,39.508313,0.044242,893.0,NaN,NaN,NaN,NaN

In [70]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['methods'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
  3c     DT   -0.0517  -0.1124  0.0089 False
  3c     RF   -0.0093   -0.07   0.0513 False
  3c     fc    0.0108  -0.0498  0.0715 False
  3c    svm   -0.1163  -0.1769 -0.0556  True
  DT     RF    0.0424  -0.0183  0.103  False
  DT     fc    0.0625   0.0019  0.1232  True
  DT    svm   -0.0646  -0.1252 -0.0039  True
  RF     fc    0.0202  -0.0405  0.0808 False
  RF    svm   -0.1069  -0.1676 -0.0463  True
  fc    svm   -0.1271  -0.1878 -0.0664  True
---------------------------------------------

# Analysis <font color=blue>after </font> combining RF, DT and SVM into 1C 
# Comparing FC (60 min) with 3C(30)

In [95]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "1c")
df.methods = df.methods.replace("['decision_tree']", "1c")
df.methods = df.methods.replace("['random_forest']", "1c")
df.drop(df[(df.methods=='fc') & ((df.time_budget==30) | (df.time_budget==10))].index, inplace=True)
df.drop(df[(df.methods=='3c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df.drop(df[(df.methods=='1c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df.shape

(300, 3)

In [96]:
rp.summary_cont(df['f1score'])

  Variable      N      Mean        SD        SE  95% Conf.  Interval
0  f1score  300.0  0.781032  0.201683  0.011644   0.758117  0.803947

In [97]:
rp.summary_cont(df.groupby(['time_budget']))['f1score']

               N      Mean        SD        SE  95% Conf.  Interval
time_budget
30           240  0.771850  0.210135  0.013564   0.745264  0.798436
60            60  0.817759  0.159848  0.020636   0.777312  0.858206

In [98]:
rp.summary_cont(df.groupby(['methods']))['f1score']

           N      Mean        SD        SE  95% Conf.  Interval
methods
1c       180  0.759652  0.222612  0.016593   0.727130  0.792173
3c        60  0.808447  0.163428  0.021098   0.767094  0.849799
fc        60  0.817759  0.159848  0.020636   0.777312  0.858206

In [99]:
rp.summary_cont(df.groupby(['time_budget', 'methods']))['f1score']

                       N      Mean        SD        SE  95% Conf.  Interval
time_budget methods
30          1c       180  0.759652  0.222612  0.016593   0.727130  0.792173
            3c        60  0.808447  0.163428  0.021098   0.767094  0.849799
60          fc        60  0.817759  0.159848  0.020636   0.777312  0.858206

In [100]:
    # Fits the model with the interaction term
    # This will also automatically include the main effects for each factor
    model = ols('f1score ~ C(time_budget)*C(methods)', df).fit()

    # Seeing if the overall model is significant
    print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 2, 297) =  2.588, p =  0.0769

In [101]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.017
Model:                            OLS   Adj. R-squared:                  0.011
Method:                 Least Squares   F-statistic:                     2.588
Date:                Wed, 23 Oct 2019   Prob (F-statistic):             0.0769
Time:                        15:04:11   Log-Likelihood:                 57.728
No. Observations:                 300   AIC:                            -109.5
Df Residuals:                     297   BIC:                            -98.34
Df Model:                           2
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                 0.7597      0.015     50.801      0.000       0.730       0.789
C(time_budget)[T.60]                      0.0194      0.010      1.943      0.053      -0.000       0.039
C(methods)[T.3c]                          0.0488      0.030      1.632      0.104      -0.010       0.108
C(methods)[T.fc]                          0.0194      0.010      1.943      0.053      -0.000       0.039
C(time_budget)[T.60]:C(methods)[T.3c]          0          0        nan        nan           0           0
C(time_budget)[T.60]:C(methods)[T.fc]     0.0194      0.010      1.943      0.053      -0.000       0.039
==============================================================================
Omnibus:                       74.811   Durbin-Watson:                   0.470
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              138.633
Skew:                          -1.338   Prob(JB):                     7.88e-31
Kurtosis:                       4.982   Cond. No.                          inf
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is      0. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [102]:
# Creates the ANOVA table
res = sm.stats.anova_lm(model, typ= 2)
res

C:\Users\HassanEldeeb\Anaconda3\lib\site-packages\statsmodels\base\model.py:1532: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 1, but rank is 0
  'rank is %d' % (J, J_), ValueWarning)
C:\Users\HassanEldeeb\Anaconda3\lib\site-packages\statsmodels\base\model.py:1532: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 2, but rank is 1
  'rank is %d' % (J, J_), ValueWarning)
C:\Users\HassanEldeeb\Anaconda3\lib\site-packages\statsmodels\base\model.py:1532: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 2, but rank is 1
  'rank is %d' % (J, J_), ValueWarning)

                                 sum_sq     df             F    PR(>F)
C(time_budget)                      NaN    1.0           NaN       NaN
C(methods)                 3.370358e-17    2.0  4.186913e-16  1.000000
C(time_budget):C(methods)  3.038849e-01    2.0  3.775087e+00  0.052966
Residual                   1.195387e+01  297.0           NaN       NaN

In [103]:
# Fits the model
model2 = ols('f1score ~ C(time_budget)+ C(methods)', df).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 2, 297) =  2.588, p =  0.0769

In [81]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.022
Model:                            OLS   Adj. R-squared:                  0.017
Method:                 Least Squares   F-statistic:                     3.765
Date:                Wed, 23 Oct 2019   Prob (F-statistic):            0.00488
Time:                        14:45:28   Log-Likelihood:                 49.945
No. Observations:                 660   AIC:                            -89.89
Df Residuals:                     655   BIC:                            -67.43
Df Model:                           4
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.7108      0.017     42.349      0.000       0.678       0.744
C(time_budget)[T.30]     0.0488      0.024      2.058      0.040       0.002       0.095
C(time_budget)[T.60]     0.0417      0.024      1.756      0.080      -0.005       0.088
C(methods)[T.3c]         0.0488      0.034      1.454      0.147      -0.017       0.115
C(methods)[T.fc]         0.0653      0.034      1.945      0.052      -0.001       0.131
==============================================================================
Omnibus:                      156.110   Durbin-Watson:                   0.424
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              294.256
Skew:                          -1.371   Prob(JB):                     1.27e-64
Kurtosis:                       4.782   Cond. No.                         4.79
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [82]:
# Creates the ANOVA table
res2 = sm.stats.anova_lm(model2, typ= 2)
res2

                   sum_sq     df         F    PR(>F)
C(time_budget)   0.250448    2.0  2.469388  0.085424
C(methods)       0.298902    2.0  2.947136  0.053186
Residual        33.215397  655.0       NaN       NaN

In [83]:
# Calculating effect size
def anova_table(aov):
    aov['mean_sq'] = aov[:]['sum_sq']/aov[:]['df']
    
    aov['eta_sq'] = aov[:-1]['sum_sq']/sum(aov['sum_sq'])
    
    aov['omega_sq'] = (aov[:-1]['sum_sq']-(aov[:-1]['df']*aov['mean_sq'][-1]))/(sum(aov['sum_sq'])+aov['mean_sq'][-1])
    
    cols = ['sum_sq', 'mean_sq', 'df', 'F', 'PR(>F)', 'eta_sq', 'omega_sq']
    aov = aov[cols]
    return aov

anova_table(res2)

,sum_sq,mean_sq,df,F,PR(>F),eta_sq,omega_sq
C(time_budget),0.250448,0.125224,2.0,2.469388,0.085424,0.007417,0.004407
C(methods),0.298902,0.149451,2.0,2.947136,0.053186,0.008852,0.005840
Residual,33.215397,0.050711,655.0,NaN,NaN,NaN,NaN

In [84]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['methods'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD,FWER=0.05
============================================
group1 group2 meandiff  lower  upper  reject
--------------------------------------------
  1C     3c    0.0675  -0.0047 0.1396 False
  1C     fc    0.0768   0.0046 0.1489  True
  3c     fc    0.0093  -0.0875 0.1061 False
--------------------------------------------

# Wilcoxon signed-rank test

In [87]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "svm")
df.methods = df.methods.replace("['decision_tree']", "DT")
df.methods = df.methods.replace("['random_forest']", "RF")
df.shape

(900, 3)

In [89]:
# Wilcoxon signed-rank test
from numpy.random import seed
from numpy.random import randn
from scipy.stats import wilcoxon
# seed the random number generator
seed(1)
# generate two independent samples
data1 = df.f1score[df.methods=='3c']
data2 = df.f1score[df.methods=='fc']
# compare samples
stat, p = wilcoxon(data1, data2)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
    print('Same distribution (fail to reject H0)')
else:
    print('Different distribution (reject H0)')

Statistics=5989.500, p=0.006
Different distribution (reject H0)

In [92]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "svm")
df.methods = df.methods.replace("['decision_tree']", "DT")
df.methods = df.methods.replace("['random_forest']", "RF")
df.shape

(900, 3)

In [94]:
# Wilcoxon signed-rank test
from numpy.random import seed
from numpy.random import randn
from scipy.stats import wilcoxon
# seed the random number generator
seed(1)
# generate two independent samples
data1 = df.f1score[df.methods=='3c']
data2 = df.f1score[df.methods=='fc']
# compare samples
stat, p = wilcoxon(data1, data2)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
    print('Same distribution (fail to reject H0)')
else:
    print('Different distribution (reject H0)')

Statistics=5989.500, p=0.006
Different distribution (reject H0)