In [1]:
import pandas
import researchpy as rp
import seaborn as sns

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

# Analysis <font color=blue>after </font> combining RF, DT and SVM into 1C

In [14]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['dataset', 'time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "1c")
df.methods = df.methods.replace("['decision_tree']", "1c")
df.methods = df.methods.replace("['random_forest']", "1c")
fsIs_b = ['vowel', 'openml_phpJNxH0q', 'dataset_31_credit-g', 'dataset_40_sonar']
fsIs_m = ['solar-flare_1', 'wine-quality-red', 'dataset_39_ecoli', 'synthetic_control']
fsIl_b = ['AirlinesCodrnaAdult', 'MagicTelescope', 'electricity-normalized', 'phpmPOD5A']
fsIl_m = ['pokerhand-normalized', 'eye_movements', 'avila-tr']
flIs_b = ['audiology', 'arrhythmia', 'AP_Breast_Lung', 'AP_Omentum_Ovary']
flIs_m = ['Amazon', 'umistfacescropped', 'phpGUrE90']
flIl_b = ['gina_agnostic', 'hiva_agnostic', 'phpZrCzJR', 'phprAeXmK']
flIl_m = ['KDDCup99', 'connect-4', 'dataset_60_waveform-5000', 'dataset_186_satimage']
df_binary = df[df.dataset.isin(fsIs_b) | df.dataset.isin(fsIl_b) | df.dataset.isin(flIs_b) | df.dataset.isin(flIl_b)]
df = df_binary
#df_multi = df[df[(((df.dataset in fsIs_m) | (df.dataset in fsIl_m)) | ((df.dataset in flIs_m) | (df.dataset in flIl_m)))].index]
#df.drop(df[(df.methods=='fc') & ((df.time_budget==30) | (df.time_budget==10))].index, inplace=True)
#df.drop(df[(df.methods=='3c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df_binary.shape

(540, 4)

In [16]:
rp.summary_cont(df['f1score'])

  Variable      N      Mean        SD        SE  95% Conf.  Interval
0  f1score  540.0  0.774845  0.228228  0.009821   0.755552  0.794138

In [19]:
rp.summary_cont(df_binary.groupby(['time_budget']))['f1score']

               N      Mean        SD        SE  95% Conf.  Interval
time_budget
10           180  0.765301  0.250066  0.018639   0.728769  0.801833
30           180  0.784569  0.219867  0.016388   0.752449  0.816689
60           180  0.774665  0.213975  0.015949   0.743406  0.805925

In [20]:
rp.summary_cont(df.groupby(['methods']))['f1score']

           N      Mean        SD        SE  95% Conf.  Interval
methods
1c       324  0.752125  0.253402  0.014078   0.724532  0.779718
3c       108  0.804413  0.181960  0.017509   0.770095  0.838731
fc       108  0.813439  0.177456  0.017076   0.779970  0.846907

In [21]:
rp.summary_cont(df.groupby(['time_budget', 'methods']))['f1score']

                       N      Mean        SD        SE  95% Conf.  Interval
time_budget methods
10          1c       108  0.736341  0.281641  0.027101   0.683223  0.789459
            3c        36  0.808008  0.186897  0.031149   0.746955  0.869061
            fc        36  0.809474  0.189506  0.031584   0.747569  0.871379
30          1c       108  0.764106  0.246618  0.023731   0.717594  0.810619
            3c        36  0.808862  0.171811  0.028635   0.752737  0.864987
            fc        36  0.821666  0.168708  0.028118   0.766554  0.876777
60          1c       108  0.755927  0.230837  0.022212   0.712391  0.799463
            3c        36  0.796369  0.191496  0.031916   0.733813  0.858924
            fc        36  0.809177  0.178304  0.029717   0.750931  0.867423

In [28]:
    # Fits the model with the interaction term
    # This will also automatically include the main effects for each factor
    model = ols('f1score ~ C(time_budget)*C(methods)', df).fit()

    # Seeing if the overall model is significant
    print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 8, 531) =  1.139, p =  0.3351

In [29]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.017
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     1.139
Date:                Fri, 01 Nov 2019   Prob (F-statistic):              0.335
Time:                        09:59:51   Log-Likelihood:                 36.669
No. Observations:                 540   AIC:                            -55.34
Df Residuals:                     531   BIC:                            -16.71
Df Model:                           8
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                 0.7363      0.022     33.564      0.000       0.693       0.779
C(time_budget)[T.30]                      0.0278      0.031      0.895      0.371      -0.033       0.089
C(time_budget)[T.60]                      0.0196      0.031      0.631      0.528      -0.041       0.081
C(methods)[T.3c]                          0.0717      0.044      1.633      0.103      -0.015       0.158
C(methods)[T.fc]                          0.0731      0.044      1.667      0.096      -0.013       0.159
C(time_budget)[T.30]:C(methods)[T.3c]    -0.0269      0.062     -0.434      0.665      -0.149       0.095
C(time_budget)[T.60]:C(methods)[T.3c]    -0.0312      0.062     -0.503      0.615      -0.153       0.091
C(time_budget)[T.30]:C(methods)[T.fc]    -0.0156      0.062     -0.251      0.802      -0.137       0.106
C(time_budget)[T.60]:C(methods)[T.fc]    -0.0199      0.062     -0.320      0.749      -0.142       0.102
==============================================================================
Omnibus:                      168.261   Durbin-Watson:                   0.310
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              369.310
Skew:                          -1.691   Prob(JB):                     6.39e-81
Kurtosis:                       5.230   Cond. No.                         11.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [30]:
# Creates the ANOVA table
res = sm.stats.anova_lm(model, typ= 2)
res

                              sum_sq     df         F    PR(>F)
C(time_budget)              0.033422    2.0  0.321482  0.725215
C(methods)                  0.422534    2.0  4.064327  0.017712
C(time_budget):C(methods)   0.017712    4.0  0.085187  0.986996
Residual                   27.601790  531.0       NaN       NaN

In [31]:
# Fits the model
model2 = ols('f1score ~ C(time_budget)+ C(methods)', df_binary).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 4, 535) =  2.208, p =  0.0669

In [32]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.016
Model:                            OLS   Adj. R-squared:                  0.009
Method:                 Least Squares   F-statistic:                     2.208
Date:                Fri, 01 Nov 2019   Prob (F-statistic):             0.0669
Time:                        10:00:24   Log-Likelihood:                 36.496
No. Observations:                 540   AIC:                            -62.99
Df Residuals:                     535   BIC:                            -41.53
Df Model:                           4
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.7426      0.019     39.662      0.000       0.706       0.779
C(time_budget)[T.30]     0.0193      0.024      0.805      0.421      -0.028       0.066
C(time_budget)[T.60]     0.0094      0.024      0.391      0.696      -0.038       0.056
C(methods)[T.3c]         0.0523      0.025      2.071      0.039       0.003       0.102
C(methods)[T.fc]         0.0613      0.025      2.429      0.015       0.012       0.111
==============================================================================
Omnibus:                      169.046   Durbin-Watson:                   0.309
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              372.703
Skew:                          -1.696   Prob(JB):                     1.17e-81
Kurtosis:                       5.249   Cond. No.                         3.96
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [33]:
# Creates the ANOVA table
res2 = sm.stats.anova_lm(model2, typ= 2)
res2

                   sum_sq     df         F    PR(>F)
C(time_budget)   0.033422    2.0  0.323696  0.723612
C(methods)       0.422534    2.0  4.092318  0.017226
Residual        27.619503  535.0       NaN       NaN

In [34]:
# Calculating effect size
def anova_table(aov):
    aov['mean_sq'] = aov[:]['sum_sq']/aov[:]['df']
    
    aov['eta_sq'] = aov[:-1]['sum_sq']/sum(aov['sum_sq'])
    
    aov['omega_sq'] = (aov[:-1]['sum_sq']-(aov[:-1]['df']*aov['mean_sq'][-1]))/(sum(aov['sum_sq'])+aov['mean_sq'][-1])
    
    cols = ['sum_sq', 'mean_sq', 'df', 'F', 'PR(>F)', 'eta_sq', 'omega_sq']
    aov = aov[cols]
    return aov

anova_table(res2)

,sum_sq,mean_sq,df,F,PR(>F),eta_sq,omega_sq
C(time_budget),0.033422,0.016711,2.0,0.323696,0.723612,0.00119,-0.002483
C(methods),0.422534,0.211267,2.0,4.092318,0.017226,0.01505,0.011351
Residual,27.619503,0.051625,535.0,NaN,NaN,NaN,NaN

In [35]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['methods'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
    1c     3c   0.0523 0.0963  -0.007 0.1115  False
    1c     fc   0.0613 0.0406  0.0021 0.1206   True
    3c     fc    0.009    0.9 -0.0636 0.0816  False
---------------------------------------------------

In [36]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['time_budget'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
    10     30   0.0193 0.6863 -0.0373 0.0759  False
    10     60   0.0094    0.9 -0.0472  0.066  False
    30     60  -0.0099    0.9 -0.0665 0.0467  False
---------------------------------------------------

# Analysis <font color=blue>without </font> combining RF, DT and SVM into 1C

In [39]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/skout.xlsx")
df = df[['dataset', 'time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['adaboost', 'bernoulli_nb', 'decision_tree', 'extra_trees', 'gaussian_nb', 'gradient_boosting', 'k_nearest_neighbors', 'lda', 'liblinear_svc', 'libsvm_svc', 'multinomial_nb', 'passive_aggressive', 'qda', 'random_forest', 'sgd']", "fc")
df.methods = df.methods.replace("['decision_tree', 'libsvm_svc', 'random_forest']", "3c")
df.methods = df.methods.replace("['libsvm_svc']", "svm")
df.methods = df.methods.replace("['decision_tree']", "DT")
df.methods = df.methods.replace("['random_forest']", "RF")
fsIs_b = ['vowel', 'openml_phpJNxH0q', 'dataset_31_credit-g', 'dataset_40_sonar']
fsIs_m = ['solar-flare_1', 'wine-quality-red', 'dataset_39_ecoli', 'synthetic_control']
fsIl_b = ['AirlinesCodrnaAdult', 'MagicTelescope', 'electricity-normalized', 'phpmPOD5A']
fsIl_m = ['pokerhand-normalized', 'eye_movements', 'avila-tr']
flIs_b = ['audiology', 'arrhythmia', 'AP_Breast_Lung', 'AP_Omentum_Ovary']
flIs_m = ['Amazon', 'umistfacescropped', 'phpGUrE90']
flIl_b = ['gina_agnostic', 'hiva_agnostic', 'phpZrCzJR', 'phprAeXmK']
flIl_m = ['KDDCup99', 'connect-4', 'dataset_60_waveform-5000', 'dataset_186_satimage']
df_binary = df[df.dataset.isin(fsIs_b) | df.dataset.isin(fsIl_b) | df.dataset.isin(flIs_b) | df.dataset.isin(flIl_b)]
df = df_binary
#df.drop(df[(df.methods=='fc') & ((df.time_budget==30) | (df.time_budget==10))].index, inplace=True)
#df.drop(df[(df.methods=='3c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df.shape

(540, 4)

In [40]:
rp.summary_cont(df['f1score'])

  Variable      N      Mean        SD        SE  95% Conf.  Interval
0  f1score  540.0  0.774845  0.228228  0.009821   0.755552  0.794138

In [41]:
rp.summary_cont(df.groupby(['time_budget']))['f1score']

               N      Mean        SD        SE  95% Conf.  Interval
time_budget
10           180  0.765301  0.250066  0.018639   0.728769  0.801833
30           180  0.784569  0.219867  0.016388   0.752449  0.816689
60           180  0.774665  0.213975  0.015949   0.743406  0.805925

In [42]:
rp.summary_cont(df.groupby(['methods']))['f1score']

           N      Mean        SD        SE  95% Conf.  Interval
methods
3c       108  0.804413  0.181960  0.017509   0.770095  0.838731
DT       108  0.771149  0.195583  0.018820   0.734262  0.808036
RF       108  0.793349  0.202158  0.019453   0.755222  0.831476
fc       108  0.813439  0.177456  0.017076   0.779970  0.846907
svm      108  0.691877  0.330111  0.031765   0.629617  0.754136

In [43]:
rp.summary_cont(df.groupby(['time_budget', 'methods']))['f1score']

                      N      Mean        SD        SE  95% Conf.  Interval
time_budget methods
10          3c       36  0.808008  0.186897  0.031149   0.746955  0.869061
            DT       36  0.764803  0.214112  0.035685   0.694860  0.834746
            RF       36  0.764667  0.258164  0.043027   0.680334  0.849001
            fc       36  0.809474  0.189506  0.031584   0.747569  0.871379
            svm      36  0.679553  0.353594  0.058932   0.564046  0.795061
30          3c       36  0.808862  0.171811  0.028635   0.752737  0.864987
            DT       36  0.779112  0.194519  0.032420   0.715569  0.842654
            RF       36  0.814875  0.178671  0.029779   0.756509  0.873241
            fc       36  0.821666  0.168708  0.028118   0.766554  0.876777
            svm      36  0.698332  0.329913  0.054986   0.590560  0.806103
60          3c       36  0.796369  0.191496  0.031916   0.733813  0.858924
            DT       36  0.769532  0.182081  0.030347   0.710052  0.829012
            RF       36  0.800505  0.158088  0.026348   0.748863  0.852147
            fc       36  0.809177  0.178304  0.029717   0.750931  0.867423
            svm      36  0.697745  0.314707  0.052451   0.594940  0.800549

In [44]:
    # Fits the model with the interaction term
    # This will also automatically include the main effects for each factor
    model = ols('f1score ~ C(time_budget)*C(methods)', df).fit()

    # Seeing if the overall model is significant
    print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 14, 525) =  1.536, p =  0.0939

In [45]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.039
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     1.536
Date:                Fri, 01 Nov 2019   Prob (F-statistic):             0.0939
Time:                        10:10:41   Log-Likelihood:                 42.912
No. Observations:                 540   AIC:                            -55.82
Df Residuals:                     525   BIC:                             8.550
Df Model:                          14
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                  0.8080      0.038     21.389      0.000       0.734       0.882
C(time_budget)[T.30]                       0.0009      0.053      0.016      0.987      -0.104       0.106
C(time_budget)[T.60]                      -0.0116      0.053     -0.218      0.828      -0.117       0.093
C(methods)[T.DT]                          -0.0432      0.053     -0.809      0.419      -0.148       0.062
C(methods)[T.RF]                          -0.0433      0.053     -0.811      0.418      -0.148       0.062
C(methods)[T.fc]                           0.0015      0.053      0.027      0.978      -0.103       0.106
C(methods)[T.svm]                         -0.1285      0.053     -2.404      0.017      -0.233      -0.024
C(time_budget)[T.30]:C(methods)[T.DT]      0.0135      0.076      0.178      0.859      -0.135       0.162
C(time_budget)[T.60]:C(methods)[T.DT]      0.0164      0.076      0.217      0.829      -0.132       0.165
C(time_budget)[T.30]:C(methods)[T.RF]      0.0494      0.076      0.653      0.514      -0.099       0.198
C(time_budget)[T.60]:C(methods)[T.RF]      0.0475      0.076      0.628      0.530      -0.101       0.196
C(time_budget)[T.30]:C(methods)[T.fc]      0.0113      0.076      0.150      0.881      -0.137       0.160
C(time_budget)[T.60]:C(methods)[T.fc]      0.0113      0.076      0.150      0.881      -0.137       0.160
C(time_budget)[T.30]:C(methods)[T.svm]     0.0179      0.076      0.237      0.813      -0.130       0.166
C(time_budget)[T.60]:C(methods)[T.svm]     0.0298      0.076      0.395      0.693      -0.119       0.178
==============================================================================
Omnibus:                      142.969   Durbin-Watson:                   0.286
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              273.780
Skew:                          -1.521   Prob(JB):                     3.54e-60
Kurtosis:                       4.708   Cond. No.                         21.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [46]:
# Creates the ANOVA table
res = sm.stats.anova_lm(model, typ= 2)
res

                              sum_sq     df         F    PR(>F)
C(time_budget)              0.033422    2.0  0.325284  0.722468
C(methods)                  1.037183    4.0  5.047296  0.000535
C(time_budget):C(methods)   0.033915    8.0  0.082521  0.999612
Residual                   26.970938  525.0       NaN       NaN

In [47]:
# Fits the model
model2 = ols('f1score ~ C(time_budget)+ C(methods)', df).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 6, 533) =  3.522, p =  0.0020

In [48]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.038
Model:                            OLS   Adj. R-squared:                  0.027
Method:                 Least Squares   F-statistic:                     3.522
Date:                Fri, 01 Nov 2019   Prob (F-statistic):            0.00199
Time:                        10:10:48   Log-Likelihood:                 42.572
No. Observations:                 540   AIC:                            -71.14
Df Residuals:                     533   BIC:                            -41.10
Df Model:                           6
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.7949      0.026     31.016      0.000       0.745       0.845
C(time_budget)[T.30]     0.0193      0.024      0.812      0.417      -0.027       0.066
C(time_budget)[T.60]     0.0094      0.024      0.395      0.693      -0.037       0.056
C(methods)[T.DT]        -0.0333      0.031     -1.086      0.278      -0.093       0.027
C(methods)[T.RF]        -0.0111      0.031     -0.361      0.718      -0.071       0.049
C(methods)[T.fc]         0.0090      0.031      0.295      0.768      -0.051       0.069
C(methods)[T.svm]       -0.1125      0.031     -3.674      0.000      -0.173      -0.052
==============================================================================
Omnibus:                      144.638   Durbin-Watson:                   0.286
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              279.680
Skew:                          -1.531   Prob(JB):                     1.86e-61
Kurtosis:                       4.749   Cond. No.                         6.45
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [49]:
# Creates the ANOVA table
res2 = sm.stats.anova_lm(model2, typ= 2)
res2

                   sum_sq     df         F    PR(>F)
C(time_budget)   0.033422    2.0  0.329826  0.719195
C(methods)       1.037183    4.0  5.117771  0.000472
Residual        27.004853  533.0       NaN       NaN

In [50]:
# Calculating effect size
def anova_table(aov):
    aov['mean_sq'] = aov[:]['sum_sq']/aov[:]['df']
    
    aov['eta_sq'] = aov[:-1]['sum_sq']/sum(aov['sum_sq'])
    
    aov['omega_sq'] = (aov[:-1]['sum_sq']-(aov[:-1]['df']*aov['mean_sq'][-1]))/(sum(aov['sum_sq'])+aov['mean_sq'][-1])
    
    cols = ['sum_sq', 'mean_sq', 'df', 'F', 'PR(>F)', 'eta_sq', 'omega_sq']
    aov = aov[cols]
    return aov

anova_table(res2)

,sum_sq,mean_sq,df,F,PR(>F),eta_sq,omega_sq
C(time_budget),0.033422,0.016711,2.0,0.329826,0.719195,0.001190,-0.002414
C(methods),1.037183,0.259296,4.0,5.117771,0.000472,0.036943,0.029671
Residual,27.004853,0.050666,533.0,NaN,NaN,NaN,NaN

In [51]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['methods'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
    3c     DT  -0.0333 0.7882  -0.117  0.0505  False
    3c     RF  -0.0111    0.9 -0.0948  0.0727  False
    3c     fc    0.009    0.9 -0.0747  0.0928  False
    3c    svm  -0.1125 0.0024 -0.1963 -0.0288   True
    DT     RF   0.0222    0.9 -0.0615  0.1059  False
    DT     fc   0.0423 0.6211 -0.0414   0.126  False
    DT    svm  -0.0793 0.0736  -0.163  0.0045  False
    RF     fc   0.0201    0.9 -0.0636  0.1038  False
    RF    svm  -0.1015 0.0086 -0.1852 -0.0177   True
    fc    svm  -0.1216  0.001 -0.2053 -0.0378   True
----------------------------------------------------