In [1]:
import pandas
import researchpy as rp
import seaborn as sns

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

# Analysis <font color=blue>after </font> combining RF, DT and SVM into 1C

In [2]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/atmout.xlsx")
df = df[['dataset', 'time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['logreg', 'svm', 'sgd', 'dt', 'et', 'rf', 'gnb', 'mnb', 'bnb', 'gp', 'pa', 'knn', 'mlp', 'ada']", "fc")
df.methods = df.methods.replace("['rf', 'dt', 'svm']", "3c")
df.methods = df.methods.replace("['logreg', 'dt', 'knn']", "def")
df.methods = df.methods.replace("['svm']", "1c")
df.methods = df.methods.replace("['dt']", "1c")
df.methods = df.methods.replace("['rf']", "1c")
fsIs_b = ['vowel', 'openml_phpJNxH0q', 'dataset_31_credit-g', 'dataset_40_sonar']
fsIs_m = ['solar-flare_1', 'wine-quality-red', 'dataset_39_ecoli', 'synthetic_control']
fsIl_b = ['AirlinesCodrnaAdult', 'MagicTelescope', 'electricity-normalized', 'phpmPOD5A']
fsIl_m = ['pokerhand-normalized', 'eye_movements', 'avila-tr']
flIs_b = ['audiology', 'arrhythmia', 'AP_Breast_Lung', 'AP_Omentum_Ovary']
flIs_m = ['Amazon', 'umistfacescropped', 'phpGUrE90']
flIl_b = ['gina_agnostic', 'hiva_agnostic', 'phpZrCzJR', 'phprAeXmK']
flIl_m = ['KDDCup99', 'connect-4', 'dataset_60_waveform-5000', 'dataset_186_satimage']
df_binary = df[df.dataset.isin(fsIs_b) | df.dataset.isin(fsIl_b) | df.dataset.isin(flIs_b) | df.dataset.isin(flIl_b)]
df_multi = df[df.dataset.isin(fsIs_m) | df.dataset.isin(fsIl_m) | df.dataset.isin(flIs_m) | df.dataset.isin(flIl_m)]
df = df_multi
#df_multi = df[df[(((df.dataset in fsIs_m) | (df.dataset in fsIl_m)) | ((df.dataset in flIs_m) | (df.dataset in flIl_m)))].index]
#df.drop(df[(df.methods=='fc') & ((df.time_budget==30) | (df.time_budget==10))].index, inplace=True)
#df.drop(df[(df.methods=='3c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df.shape

(292, 4)

In [3]:
rp.summary_cont(df['f1score'])

  Variable      N    Mean      SD        SE  95% Conf.  Interval
0  f1score  292.0  0.7582  0.1613  0.009439   0.739622  0.776778

In [4]:
rp.summary_cont(df.groupby(['time_budget']))['f1score']

               N      Mean        SD        SE  95% Conf.  Interval
time_budget
10            79  0.725134  0.143834  0.016183   0.693416  0.756852
30           114  0.763673  0.180783  0.016932   0.730487  0.796860
60            99  0.778282  0.147587  0.014833   0.749209  0.807355

In [5]:
rp.summary_cont(df.groupby(['methods']))['f1score']

           N      Mean        SD        SE  95% Conf.  Interval
methods
1c       174  0.755227  0.170603  0.012933   0.729878  0.780577
3c        28  0.768372  0.128056  0.024200   0.720939  0.815804
def       39  0.753630  0.148560  0.023789   0.707005  0.800256
fc        51  0.766250  0.157859  0.022105   0.722925  0.809576

In [6]:
rp.summary_cont(df.groupby(['time_budget', 'methods']))['f1score']

                      N      Mean        SD        SE  95% Conf.  Interval
time_budget methods
10          1c       41  0.742490  0.133340  0.020824   0.701675  0.783306
            3c        4  0.705839  0.064482  0.032241   0.642646  0.769031
            def      12  0.744173  0.191095  0.055164   0.636051  0.852295
            fc       22  0.685912  0.144140  0.030731   0.625680  0.746145
30          1c       75  0.751913  0.199818  0.023073   0.706690  0.797137
            3c       11  0.758578  0.127550  0.038458   0.683201  0.833955
            def      12  0.766598  0.130322  0.037621   0.692861  0.840335
            fc       16  0.820107  0.147711  0.036928   0.747728  0.892485
60          1c       58  0.768516  0.153994  0.020220   0.728884  0.808148
            3c       13  0.795900  0.141728  0.039308   0.718856  0.872944
            def      15  0.750822  0.132809  0.034291   0.683611  0.818032
            fc       13  0.835922  0.138710  0.038471   0.760519  0.911326

In [7]:
    # Fits the model with the interaction term
    # This will also automatically include the main effects for each factor
    model = ols('f1score ~ C(time_budget)*C(methods)', df).fit()

    # Seeing if the overall model is significant
    print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 11, 280) =  1.078, p =  0.3792

In [8]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.041
Model:                            OLS   Adj. R-squared:                  0.003
Method:                 Least Squares   F-statistic:                     1.078
Date:                Fri, 01 Nov 2019   Prob (F-statistic):              0.379
Time:                        17:27:08   Log-Likelihood:                 124.98
No. Observations:                 292   AIC:                            -226.0
Df Residuals:                     280   BIC:                            -181.8
Df Model:                          11
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                  0.7425      0.025     29.518      0.000       0.693       0.792
C(time_budget)[T.30]                       0.0094      0.031      0.301      0.763      -0.052       0.071
C(time_budget)[T.60]                       0.0260      0.033      0.792      0.429      -0.039       0.091
C(methods)[T.3c]                          -0.0367      0.084     -0.434      0.664      -0.203       0.129
C(methods)[T.def]                          0.0017      0.053      0.032      0.975      -0.102       0.106
C(methods)[T.fc]                          -0.0566      0.043     -1.329      0.185      -0.140       0.027
C(time_budget)[T.30]:C(methods)[T.3c]      0.0433      0.099      0.437      0.662      -0.152       0.238
C(time_budget)[T.60]:C(methods)[T.3c]      0.0640      0.098      0.655      0.513      -0.128       0.257
C(time_budget)[T.30]:C(methods)[T.def]     0.0130      0.073      0.179      0.858      -0.130       0.156
C(time_budget)[T.60]:C(methods)[T.def]    -0.0194      0.071     -0.275      0.784      -0.158       0.119
C(time_budget)[T.30]:C(methods)[T.fc]      0.1248      0.061      2.030      0.043       0.004       0.246
C(time_budget)[T.60]:C(methods)[T.fc]      0.1240      0.065      1.901      0.058      -0.004       0.252
==============================================================================
Omnibus:                       14.769   Durbin-Watson:                   2.523
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.448
Skew:                          -0.362   Prob(JB):                     2.20e-05
Kurtosis:                       4.113   Cond. No.                         19.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
# Creates the ANOVA table
res = sm.stats.anova_lm(model, typ= 2)
res

                             sum_sq     df         F    PR(>F)
C(time_budget)             0.137719    2.0  2.654416  0.072110
C(methods)                 0.016558    3.0  0.212764  0.887518
C(time_budget):C(methods)  0.161261    6.0  1.036052  0.402025
Residual                   7.263626  280.0       NaN       NaN

In [10]:
# Fits the model
model2 = ols('f1score ~ C(time_budget)+ C(methods)', df).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 5, 286) =  1.127, p =  0.3462

In [11]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.019
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     1.127
Date:                Fri, 01 Nov 2019   Prob (F-statistic):              0.346
Time:                        17:27:08   Log-Likelihood:                 121.77
No. Observations:                 292   AIC:                            -231.5
Df Residuals:                     286   BIC:                            -209.5
Df Model:                           5
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.7190      0.021     34.990      0.000       0.679       0.759
C(time_budget)[T.30]     0.0410      0.024      1.714      0.088      -0.006       0.088
C(time_budget)[T.60]     0.0555      0.025      2.249      0.025       0.007       0.104
C(methods)[T.3c]         0.0074      0.033      0.226      0.821      -0.057       0.072
C(methods)[T.def]        0.0006      0.029      0.021      0.983      -0.056       0.057
C(methods)[T.fc]         0.0202      0.026      0.776      0.438      -0.031       0.071
==============================================================================
Omnibus:                       14.854   Durbin-Watson:                   2.457
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               20.921
Skew:                          -0.376   Prob(JB):                     2.86e-05
Kurtosis:                       4.074   Cond. No.                         4.66
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [12]:
# Creates the ANOVA table
res2 = sm.stats.anova_lm(model2, typ= 2)
res2

                  sum_sq     df         F    PR(>F)
C(time_budget)  0.137719    2.0  2.652410  0.072215
C(methods)      0.016558    3.0  0.212604  0.887631
Residual        7.424887  286.0       NaN       NaN

In [13]:
# Calculating effect size
def anova_table(aov):
    aov['mean_sq'] = aov[:]['sum_sq']/aov[:]['df']
    
    aov['eta_sq'] = aov[:-1]['sum_sq']/sum(aov['sum_sq'])
    
    aov['omega_sq'] = (aov[:-1]['sum_sq']-(aov[:-1]['df']*aov['mean_sq'][-1]))/(sum(aov['sum_sq'])+aov['mean_sq'][-1])
    
    cols = ['sum_sq', 'mean_sq', 'df', 'F', 'PR(>F)', 'eta_sq', 'omega_sq']
    aov = aov[cols]
    return aov

anova_table(res2)

,sum_sq,mean_sq,df,F,PR(>F),eta_sq,omega_sq
C(time_budget),0.137719,0.068860,2.0,2.652410,0.072215,0.018171,0.011281
C(methods),0.016558,0.005519,3.0,0.212604,0.887631,0.002185,-0.008064
Residual,7.424887,0.025961,286.0,NaN,NaN,NaN,NaN

In [14]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['methods'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
==================================================
group1 group2 meandiff p-adj  lower  upper  reject
--------------------------------------------------
    1c     3c   0.0131   0.9 -0.0721 0.0984  False
    1c    def  -0.0016   0.9 -0.0758 0.0726  False
    1c     fc    0.011   0.9 -0.0557 0.0777  False
    3c    def  -0.0147   0.9 -0.1185  0.089  False
    3c     fc  -0.0021   0.9 -0.1006 0.0964  False
   def     fc   0.0126   0.9 -0.0765 0.1017  False
--------------------------------------------------

In [15]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['time_budget'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
    10     30   0.0385 0.2306 -0.0168 0.0939  False
    10     60   0.0531 0.0737 -0.0039 0.1102  False
    30     60   0.0146 0.7651 -0.0373 0.0665  False
---------------------------------------------------

# Analysis <font color=blue>without </font> combining RF, DT and SVM into 1C

In [16]:
df = pandas.read_excel(r"C:\Users\HassanEldeeb\Documents\GitHub\AutoMLBenchmarking\logs_search_space/atmout.xlsx")
df = df[['dataset', 'time_budget', 'methods', 'f1score']]
df.methods = df.methods.replace("['logreg', 'svm', 'sgd', 'dt', 'et', 'rf', 'gnb', 'mnb', 'bnb', 'gp', 'pa', 'knn', 'mlp', 'ada']", "fc")
df.methods = df.methods.replace("['rf', 'dt', 'svm']", "3c")
df.methods = df.methods.replace("['logreg', 'dt', 'knn']", "def")
df.methods = df.methods.replace("['svm']", "svm")
df.methods = df.methods.replace("['dt']", "dt")
df.methods = df.methods.replace("['rf']", "rf")
fsIs_b = ['vowel', 'openml_phpJNxH0q', 'dataset_31_credit-g', 'dataset_40_sonar']
fsIs_m = ['solar-flare_1', 'wine-quality-red', 'dataset_39_ecoli', 'synthetic_control']
fsIl_b = ['AirlinesCodrnaAdult', 'MagicTelescope', 'electricity-normalized', 'phpmPOD5A']
fsIl_m = ['pokerhand-normalized', 'eye_movements', 'avila-tr']
flIs_b = ['audiology', 'arrhythmia', 'AP_Breast_Lung', 'AP_Omentum_Ovary']
flIs_m = ['Amazon', 'umistfacescropped', 'phpGUrE90']
flIl_b = ['gina_agnostic', 'hiva_agnostic', 'phpZrCzJR', 'phprAeXmK']
flIl_m = ['KDDCup99', 'connect-4', 'dataset_60_waveform-5000', 'dataset_186_satimage']
df_binary = df[df.dataset.isin(fsIs_b) | df.dataset.isin(fsIl_b) | df.dataset.isin(flIs_b) | df.dataset.isin(flIl_b)]
df_multi = df[df.dataset.isin(fsIs_m) | df.dataset.isin(fsIl_m) | df.dataset.isin(flIs_m) | df.dataset.isin(flIl_m)]
df = df_multi
#df.drop(df[(df.methods=='fc') & ((df.time_budget==30) | (df.time_budget==10))].index, inplace=True)
#df.drop(df[(df.methods=='3c') & ((df.time_budget==60) | (df.time_budget==10))].index, inplace=True)
df.shape

(292, 4)

In [17]:
rp.summary_cont(df['f1score'])

  Variable      N    Mean      SD        SE  95% Conf.  Interval
0  f1score  292.0  0.7582  0.1613  0.009439   0.739622  0.776778

In [18]:
rp.summary_cont(df.groupby(['time_budget']))['f1score']

               N      Mean        SD        SE  95% Conf.  Interval
time_budget
10            79  0.725134  0.143834  0.016183   0.693416  0.756852
30           114  0.763673  0.180783  0.016932   0.730487  0.796860
60            99  0.778282  0.147587  0.014833   0.749209  0.807355

In [19]:
rp.summary_cont(df.groupby(['methods']))['f1score']

          N      Mean        SD        SE  95% Conf.  Interval
methods
3c       28  0.768372  0.128056  0.024200   0.720939  0.815804
def      39  0.753630  0.148560  0.023789   0.707005  0.800256
dt       63  0.764606  0.156046  0.019660   0.726072  0.803140
fc       51  0.766250  0.157859  0.022105   0.722925  0.809576
rf       68  0.792753  0.134527  0.016314   0.760778  0.824728
svm      43  0.682144  0.217233  0.033128   0.617213  0.747074

In [20]:
rp.summary_cont(df.groupby(['time_budget', 'methods']))['f1score']

                      N      Mean        SD        SE  95% Conf.  Interval
time_budget methods
10          3c        4  0.705839  0.064482  0.032241   0.642646  0.769031
            def      12  0.744173  0.191095  0.055164   0.636051  0.852295
            dt       22  0.766530  0.154708  0.032984   0.701881  0.831178
            fc       22  0.685912  0.144140  0.030731   0.625680  0.746145
            rf       13  0.733893  0.103668  0.028752   0.677538  0.790247
            svm       6  0.672975  0.085937  0.035083   0.604211  0.741738
30          3c       11  0.758578  0.127550  0.038458   0.683201  0.833955
            def      12  0.766598  0.130322  0.037621   0.692861  0.840335
            dt       20  0.764191  0.165296  0.036961   0.691747  0.836635
            fc       16  0.820107  0.147711  0.036928   0.747728  0.892485
            rf       36  0.805641  0.140587  0.023431   0.759716  0.851566
            svm      19  0.637191  0.277561  0.063677   0.512384  0.761997
60          3c       13  0.795900  0.141728  0.039308   0.718856  0.872944
            def      15  0.750822  0.132809  0.034291   0.683611  0.818032
            dt       21  0.762986  0.156178  0.034081   0.696187  0.829784
            fc       13  0.835922  0.138710  0.038471   0.760519  0.911326
            rf       19  0.808606  0.136630  0.031345   0.747169  0.870042
            svm      18  0.732650  0.166896  0.039338   0.655548  0.809753

In [21]:
    # Fits the model with the interaction term
    # This will also automatically include the main effects for each factor
    model = ols('f1score ~ C(time_budget)*C(methods)', df).fit()

    # Seeing if the overall model is significant
    print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 17, 274) =  1.802, p =  0.0276

In [22]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.101
Model:                            OLS   Adj. R-squared:                  0.045
Method:                 Least Squares   F-statistic:                     1.802
Date:                Fri, 01 Nov 2019   Prob (F-statistic):             0.0276
Time:                        17:27:08   Log-Likelihood:                 134.40
No. Observations:                 292   AIC:                            -232.8
Df Residuals:                     274   BIC:                            -166.6
Df Model:                          17
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                  0.7058      0.079      8.955      0.000       0.551       0.861
C(time_budget)[T.30]                       0.0527      0.092      0.573      0.567      -0.128       0.234
C(time_budget)[T.60]                       0.0901      0.090      0.999      0.319      -0.087       0.268
C(methods)[T.def]                          0.0383      0.091      0.421      0.674      -0.141       0.218
C(methods)[T.dt]                           0.0607      0.086      0.708      0.479      -0.108       0.229
C(methods)[T.fc]                          -0.0199      0.086     -0.233      0.816      -0.189       0.149
C(methods)[T.rf]                           0.0281      0.090      0.311      0.756      -0.149       0.206
C(methods)[T.svm]                         -0.0329      0.102     -0.323      0.747      -0.233       0.167
C(time_budget)[T.30]:C(methods)[T.def]    -0.0303      0.112     -0.270      0.787      -0.251       0.191
C(time_budget)[T.60]:C(methods)[T.def]    -0.0834      0.109     -0.766      0.444      -0.298       0.131
C(time_budget)[T.30]:C(methods)[T.dt]     -0.0551      0.104     -0.529      0.597      -0.260       0.150
C(time_budget)[T.60]:C(methods)[T.dt]     -0.0936      0.102     -0.916      0.360      -0.295       0.108
C(time_budget)[T.30]:C(methods)[T.fc]      0.0815      0.106      0.771      0.441      -0.126       0.289
C(time_budget)[T.60]:C(methods)[T.fc]      0.0599      0.106      0.567      0.571      -0.148       0.268
C(time_budget)[T.30]:C(methods)[T.rf]      0.0190      0.105      0.181      0.857      -0.188       0.226
C(time_budget)[T.60]:C(methods)[T.rf]     -0.0153      0.107     -0.144      0.886      -0.225       0.194
C(time_budget)[T.30]:C(methods)[T.svm]    -0.0885      0.118     -0.750      0.454      -0.321       0.144
C(time_budget)[T.60]:C(methods)[T.svm]    -0.0304      0.117     -0.260      0.795      -0.260       0.200
==============================================================================
Omnibus:                        0.430   Durbin-Watson:                   2.681
Prob(Omnibus):                  0.806   Jarque-Bera (JB):                0.244
Skew:                          -0.049   Prob(JB):                        0.885
Kurtosis:                       3.103   Cond. No.                         47.5
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [23]:
# Creates the ANOVA table
res = sm.stats.anova_lm(model, typ= 2)
res

                             sum_sq     df         F    PR(>F)
C(time_budget)             0.176295    2.0  3.546813  0.030147
C(methods)                 0.386103    5.0  3.107135  0.009567
C(time_budget):C(methods)  0.245716   10.0  0.988693  0.453431
Residual                   6.809626  274.0       NaN       NaN

In [24]:
# Fits the model
model2 = ols('f1score ~ C(time_budget)+ C(methods)', df).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 7, 284) =  2.966, p =  0.0051

In [25]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                f1score   R-squared:                       0.068
Model:                            OLS   Adj. R-squared:                  0.045
Method:                 Least Squares   F-statistic:                     2.966
Date:                Fri, 01 Nov 2019   Prob (F-statistic):            0.00512
Time:                        17:27:08   Log-Likelihood:                 129.22
No. Observations:                 292   AIC:                            -242.4
Df Residuals:                     284   BIC:                            -213.0
Df Model:                           7
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.7212      0.035     20.602      0.000       0.652       0.790
C(time_budget)[T.30]     0.0443      0.024      1.866      0.063      -0.002       0.091
C(time_budget)[T.60]     0.0641      0.024      2.634      0.009       0.016       0.112
C(methods)[T.def]       -0.0059      0.039     -0.150      0.881      -0.083       0.071
C(methods)[T.dt]         0.0080      0.036      0.221      0.825      -0.063       0.079
C(methods)[T.fc]         0.0148      0.038      0.394      0.694      -0.059       0.089
C(methods)[T.rf]         0.0302      0.036      0.848      0.397      -0.040       0.100
C(methods)[T.svm]       -0.0855      0.038     -2.232      0.026      -0.161      -0.010
==============================================================================
Omnibus:                        2.416   Durbin-Watson:                   2.578
Prob(Omnibus):                  0.299   Jarque-Bera (JB):                2.150
Skew:                          -0.142   Prob(JB):                        0.341
Kurtosis:                       3.310   Cond. No.                         10.1
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [26]:
# Creates the ANOVA table
res2 = sm.stats.anova_lm(model2, typ= 2)
res2

                  sum_sq     df         F    PR(>F)
C(time_budget)  0.176295    2.0  3.548225  0.030058
C(methods)      0.386103    5.0  3.108373  0.009498
Residual        7.055343  284.0       NaN       NaN

In [27]:
# Calculating effect size
def anova_table(aov):
    aov['mean_sq'] = aov[:]['sum_sq']/aov[:]['df']
    
    aov['eta_sq'] = aov[:-1]['sum_sq']/sum(aov['sum_sq'])
    
    aov['omega_sq'] = (aov[:-1]['sum_sq']-(aov[:-1]['df']*aov['mean_sq'][-1]))/(sum(aov['sum_sq'])+aov['mean_sq'][-1])
    
    cols = ['sum_sq', 'mean_sq', 'df', 'F', 'PR(>F)', 'eta_sq', 'omega_sq']
    aov = aov[cols]
    return aov

anova_table(res2)

,sum_sq,mean_sq,df,F,PR(>F),eta_sq,omega_sq
C(time_budget),0.176295,0.088148,2.0,3.548225,0.030058,0.023143,0.016566
C(methods),0.386103,0.077221,5.0,3.108373,0.009498,0.050685,0.034267
Residual,7.055343,0.024843,284.0,NaN,NaN,NaN,NaN

In [28]:
mc = statsmodels.stats.multicomp.MultiComparison(df['f1score'], df['methods'])
mc_results = mc.tukeyhsd()
print(mc_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
    3c    def  -0.0147    0.9 -0.1278  0.0983  False
    3c     dt  -0.0038    0.9 -0.1074  0.0999  False
    3c     fc  -0.0021    0.9 -0.1094  0.1052  False
    3c     rf   0.0244    0.9 -0.0781  0.1268  False
    3c    svm  -0.0862  0.226  -0.197  0.0246  False
   def     dt    0.011    0.9  -0.082  0.1039  False
   def     fc   0.0126    0.9 -0.0844  0.1097  False
   def     rf   0.0391 0.8011 -0.0525  0.1308  False
   def    svm  -0.0715  0.326 -0.1724  0.0294  False
    dt     fc   0.0016    0.9 -0.0843  0.0876  False
    dt     rf   0.0281    0.9 -0.0516  0.1079  False
    dt    svm  -0.0825 0.0952 -0.1727  0.0078  False
    fc     rf   0.0265    0.9  -0.058   0.111  False
    fc    svm  -0.0841 0.1123 -0.1786  0.0103  False
    rf    svm  -0.1106 0.0055 -0.1995 -0.0217   True
----------------------------------------------------